kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: ubuntu:latest
    commands:
      - apt-get update && apt-get install -y --no-install-recommends python3 python3-pip python3-dev python3-venv libmariadb-dev build-essential
      - python3 -m venv venv
      - . venv/bin/activate
      - pip install --upgrade pip wheel setuptools
      - pip install poetry
      - poetry install
      - poetry build
    when:
      event:
        exclude:
          - promote
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: suprachat.net
      username: suprabot
      key:
        from_secret: ssh-key-suprabot
      port: 39901
      command_timeout: 2m
      script:
        - sh deploy-suprabot.sh
    when:
      branch:
        - main
      event:
        - promote
