kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: ubuntu:latest
    commands:
      - apt-get update && apt-get install -y --no-install-recommends python3 python3-venv libmariadb-dev
      - pip install --upgrade pip wheel setuptools
      - pip install poetry
      - poetry install
      - poetry build
      - pip install dist/*.whl
