kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: mariadb:latest
    commands:
      - apt update && apt install -y --no-install-recommends python3
      - python3 -m venv venv
      - . venv/bin/activate
      - pip install --upgrade pip wheel setuptools
      - pip install poetry
      - poetry install
      - poetry build
      - pip install dist *.whl
