kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: ubuntu:latest
    commands:
      - apt-get update && apt-get install -y --no-install-recommends python3 python3-venv libmariadb-dev
      - pip3 install --upgrade pip wheel setuptools
      - pip3 install poetry
      - poetry install
      - poetry build
      - pip3 install dist/*.whl
