kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: archlinux:base-devel
    commands:
      - sh -c "pacman -S python mariadb"
      - python -m venv venv
      - . venv/bin/activate
      - pip install --upgrade pip wheel setuptools
      - pip install poetry
      - poetry install
      - poetry build
      - pip install dist *.whl
